/* Generated by ingot v{{ version }} — do not edit.
 *
 * UDM-compat alias (P2-20260707-014 Gap A): the dropped gen/udm codegen emitted the
 * boolean-storage getter/setter declarations under this filename
 * (BooleanStorage_SetKey/BooleanStorage_GetKey + BOOLEAN_STORAGE_NUM_KEYS). Several
 * libBissellIoT call sites (telemetry.c, endpoint_handler.c, local_comm.c, udm_comm.c)
 * still #include "dm_boolean_storage.h" verbatim. Ingot's own boolean_storage.h exposes
 * the identical signatures, so this header repoints to it rather than being
 * hand-maintained in the lib tree.
 */
#ifndef INGOT_DM_BOOLEAN_STORAGE_H
#define INGOT_DM_BOOLEAN_STORAGE_H

#include "boolean_storage.h"

#endif /* INGOT_DM_BOOLEAN_STORAGE_H */
