/* Generated by ingot v{{ version }} — do not edit */
#ifndef INGOT_DM_ENUMS_H
#define INGOT_DM_ENUMS_H

#ifdef __cplusplus
extern "C" {
#endif
{% for e in enums %}
{%- if e.doc %}
/* {{ e.doc }} */
{%- endif %}
typedef enum {
{% for m in e.members %}    {{ m.name }} = {{ m.value }}{% if not loop.last %},{% endif %}
{% endfor %}} {{ e.type_name }};
{% endfor %}
#ifdef __cplusplus
}
#endif

#endif /* INGOT_DM_ENUMS_H */
