/* Generated by ingot v{{ version }} — do not edit */
#ifndef INGOT_DM_ENUMS_H
#define INGOT_DM_ENUMS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif
{% for e in enums %}

typedef enum {
{% for c in e.values %}    {{ c.name }} = {{ c.value }},
{% endfor %}    {{ e.prefix }}_MAX_STORAGE_VALUE = {{ e.max_macro }}
} {{ e.type_name }};
{% endfor %}

#ifdef __cplusplus
}
#endif

#endif /* INGOT_DM_ENUMS_H */
