/* Generated by ingot v{{ version }} — do not edit */
#include "dm_helpers.h"
{% for h in helpers %}
{% if h.is_string %}

const char *DataModel_Get_{{ h.helper_name }}(void)
{
    const char *val = NULL;
    DataModel_GetStringByKey({{ h.define_name }}, &val);
    return val;
}
{% if not h.is_read_only %}

DM_RETURN_CODE DataModel_Set_{{ h.helper_name }}(const char *val)
{
    return DataModel_SetStringByKey({{ h.define_name }}, val);
}
{% endif %}
{% endif %}
{% endfor %}
