/* Generated by ingot v{{ version }} — do not edit.
 *
 * UDM-compat alias (P2-20260707-014, sibling of Gap A): the dropped gen/udm codegen emitted the
 * integer-storage getter/setter declarations under this filename
 * (IntegerStorage_Set/GetUINT8Key/etc.). Several libBissellIoT call sites (telemetry.c,
 * endpoint_handler.c, local_comm.c) still #include "dm_integer_storage.h" verbatim. Ingot's own
 * integer_storage.h exposes the identical signatures, so this header repoints to it rather than
 * being hand-maintained in the lib tree.
 */
#ifndef INGOT_DM_INTEGER_STORAGE_H
#define INGOT_DM_INTEGER_STORAGE_H

#include "integer_storage.h"

#endif /* INGOT_DM_INTEGER_STORAGE_H */
