/* Generated by ingot v{{ version }} — do not edit.
 *
 * UDM-compat alias (P2-20260707-006): behavior-identical replacement for the
 * dropped gen/udm/dm_key_events.c. Forwards to the ingot-native
 * send_tinyfsm_event_by_key dispatch table (dm_key_events_wrapper.cpp) so
 * every existing send_dm_key_event(key) call site keeps working unchanged.
 */
#include "dm_key_events.h"

#include "dm_key_events_wrapper.hpp"

void send_dm_key_event(uint32_t key_id)
{
    send_tinyfsm_event_by_key(key_id);
}
