/* Generated by ingot v{{ version }} — do not edit.
 *
 * UDM-compat alias (P2-20260707-006): the dropped gen/udm codegen used to emit the bare-key
 * #defines under this filename. libBissellIoT's call sites still #include "dm_key_definitions.h"
 * verbatim, so this header repoints to the canonical ingot output (key_definitions.h) rather than
 * being hand-maintained in the lib tree.
 */
#ifndef INGOT_DM_KEY_DEFINITIONS_H
#define INGOT_DM_KEY_DEFINITIONS_H

#include "key_definitions.h"

#endif /* INGOT_DM_KEY_DEFINITIONS_H */
