/* Generated by ingot v{{ version }} — do not edit.
 *
 * UDM-compat alias (P2-20260707-006): the dropped gen/udm codegen used to emit
 * `send_dm_key_event(uint32_t)` under this filename, backed by its own
 * dm_key_events.c. libBissellIoT's call sites (bissell_iot.cpp,
 * durableInterface.c) still unconditionally #include "dm_key_events.h" and
 * call send_dm_key_event(key) directly — this header + its companion
 * dm_key_events.c reproduce that C-linkage surface on top of the ingot-native
 * dm_key_events_wrapper (send_tinyfsm_event_by_key), so those call sites
 * compile and link unchanged.
 */
#ifndef INGOT_DM_KEY_EVENTS_H
#define INGOT_DM_KEY_EVENTS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

void send_dm_key_event(uint32_t key_id);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* INGOT_DM_KEY_EVENTS_H */
