/* Generated by ingot v{{ version }} — do not edit */
#ifndef INGOT_DM_KEY_EVENTS_HPP
#define INGOT_DM_KEY_EVENTS_HPP

#include "tinyfsm.hpp"

#ifdef __cplusplus
extern "C" {
#endif
{% for group in groups %}

// namespace: {{ group.namespace }}, class: {{ group.class }}
{% for ev in group.events %}struct {{ ev }} : tinyfsm::Event { };
{% endfor %}{% endfor %}

#ifdef __cplusplus
}
#endif

#endif /* INGOT_DM_KEY_EVENTS_HPP */
