/* Generated by ingot v{{ version }} — do not edit */
#ifndef INGOT_DM_KEY_HAS_EVENT_HPP
#define INGOT_DM_KEY_HAS_EVENT_HPP

#include <stdbool.h>
#include <stdint.h>

#include "key_definitions.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Whether a data-model key carries a tinyfsm event, i.e. was declared
 * `event = true` in the model TOML.
 *
 * WHY THIS EXISTS. `event = false` was already honoured HERE, at code generation:
 * dm_key_events.hpp emits an FSM_EVENT_ struct only for event keys, so a non-event
 * key has nothing to react to and never could. But a consumer's value-change
 * callback fires for EVERY changed key, and with no way to ask which keys matter it
 * had to enqueue all of them. The declaration was therefore true of the generated
 * types and false of the runtime traffic.
 *
 * Measured on the B12 robot 2026-08-21: a sustained mapping run produced 103079
 * dropped events on a 1024-deep dispatch queue, of which the single loudest key was
 * DM_KEY_B12_ODOM_MS_TIMER_100HZ — a free-running 100 Hz millisecond counter that
 * changes on every MCU frame BY CONSTRUCTION and so can never be deduplicated. It
 * is declared `event = false`. Nothing reacts to it, nothing ever could, and it was
 * still costing a queue slot 100 times a second while real reactions were dropped.
 *
 * Gate the enqueue on this and non-event keys stop consuming the bus. It is a
 * switch over compile-time constants, so the compiler lowers it to a jump table or
 * binary search rather than a linear scan.
 */
/*
 * The namespace a key belongs to, and the namespace THIS model generates.
 *
 * Layout is ingot's own, from src/model/key.rs: the namespace occupies the top bits of the
 * key id (`(namespace & 0x3FF) << 22`). Exposed here rather than left for a consumer to
 * rediscover, because the alternative is a hand-derived numeric range in consumer code --
 * a magic number that silently rots the first time a namespace is added.
 *
 * WHY A CONSUMER WANTS THIS. dm_key_has_event() alone is not a safe enqueue filter for a
 * process that fans key changes to MORE than its own FSM dispatch: a foreign consumer may
 * read keys this model says nothing about. Pairing the two IS safe -- "in MY namespace and
 * carrying no event" is a key that only this model's own FSM layer could have wanted, and
 * that layer provably does not, because no event struct exists for it.
 */
#define DM_KEY_NS_SHIFT 22U
#define DM_KEY_NS_MASK 0x3FFU
#define DM_KEY_NS_LOCAL {{ ns_id }}U

static inline uint32_t dm_key_namespace(uint32_t key)
{
    return (key >> DM_KEY_NS_SHIFT) & DM_KEY_NS_MASK;
}

static inline bool dm_key_has_event(uint32_t key)
{
    switch (key) {
{%- for ev in events %}
    case {{ ev.define_name }}:
{%- endfor %}
        return true;

    default:
        return false;
    }
}

#ifdef __cplusplus
}
#endif

#endif /* INGOT_DM_KEY_HAS_EVENT_HPP */
