/* Generated by ingot v{{ version }} — do not edit */
#ifndef INGOT_DM_NAMESPACE_DEFINITIONS_H
#define INGOT_DM_NAMESPACE_DEFINITIONS_H

#ifdef __cplusplus
extern "C" {
#endif

#define DM_NAMESPACE_{{ namespace_upper }} {{ ns_id }}U

#ifdef __cplusplus
}
#endif

#endif /* INGOT_DM_NAMESPACE_DEFINITIONS_H */
