/* Generated by ingot v{{ version }} — do not edit */
#ifndef INGOT_DM_NAMESPACE_DEFINITIONS_H
#define INGOT_DM_NAMESPACE_DEFINITIONS_H

#ifdef __cplusplus
extern "C" {
#endif

{% for ns in namespaces %}
#define DM_NAMESPACE_{{ ns.namespace_upper }} {{ ns.ns_id }}U
{% endfor %}

#ifdef __cplusplus
}
#endif

#endif /* INGOT_DM_NAMESPACE_DEFINITIONS_H */
