/* Generated by ingot v{{ version }} — do not edit.
 *
 * UDM-compat alias (P2-20260707-006/014): the dropped gen/udm codegen emitted persistence-storage
 * declarations under this filename. libBissellIoT's endpoint_handler.c includes this header
 * without calling a PersistenceStorage/DataModel persistent-keys function directly, but
 * local_comm.c's eng-debug endpoint DOES call DataModel_PrintPersistentKeys() (guarded behind
 * -DDATAMODEL_PRINT_PERSISTENT_KEYS, which the lib's CMakeLists.txt always defines) — found via a
 * real aarch64 device build, not a host build (host never links that TU). This repoints to
 * ingot's own persistence_storage.h, which now emits that function for real.
 */
#ifndef INGOT_DM_PERSISTENCE_STORAGE_H
#define INGOT_DM_PERSISTENCE_STORAGE_H

#include "persistence_storage.h"

#endif /* INGOT_DM_PERSISTENCE_STORAGE_H */
