/* Generated by ingot v{{ version }} — do not edit.
 *
 * UDM-compat alias (P2-20260707-014, sibling of Gap A): the dropped gen/udm codegen emitted
 * persistence-storage declarations under this filename. libBissellIoT's endpoint_handler.c and
 * local_comm.c include "dm_persistence_storage.h" without calling any PersistenceStorage or
 * DataModel persistent-keys function directly (same pattern as the other dm storage aliases),
 * so this repoints to ingot's own persistence_storage.h rather than being hand-maintained.
 */
#ifndef INGOT_DM_PERSISTENCE_STORAGE_H
#define INGOT_DM_PERSISTENCE_STORAGE_H

#include "persistence_storage.h"

#endif /* INGOT_DM_PERSISTENCE_STORAGE_H */
