/* Generated by ingot v{{ version }} — do not edit.
 *
 * UDM-compat alias (P2-20260707-014, sibling of Gap A): the dropped gen/udm codegen emitted
 * string-storage declarations under this filename. libBissellIoT's telemetry.c,
 * endpoint_handler.c, and local_comm.c #include "dm_string_storage.h" without calling any
 * StringStorage_* function directly (same pattern as dm_boolean_storage.h/dm_integer_storage.h),
 * so this repoints to ingot's own string_storage.h rather than being hand-maintained.
 */
#ifndef INGOT_DM_STRING_STORAGE_H
#define INGOT_DM_STRING_STORAGE_H

#include "string_storage.h"

#endif /* INGOT_DM_STRING_STORAGE_H */
