/* Generated by ingot v{{ version }} — do not edit */
#ifndef INGOT_INTEGER_STORAGE_H
#define INGOT_INTEGER_STORAGE_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif
{% for t in types %}

/* {{ t.label }} storage: {{ t.num_keys }} keys */
#define {{ t.PREFIX }}_STORAGE_NUM_KEYS {{ t.num_keys }}U

bool IntegerStorage_Set{{ t.suffix }}Key(uint32_t key, {{ t.c_type }} value);
bool IntegerStorage_Get{{ t.suffix }}Key(uint32_t key, {{ t.c_type }} *result);
{% endfor %}

#define INTEGER_STORAGE_NUM_KEYS (
{%- for t in types %}{{ t.PREFIX }}_STORAGE_NUM_KEYS{% if not loop.last %} + {% endif %}{% endfor %})

#ifdef __cplusplus
}
#endif

#endif /* INGOT_INTEGER_STORAGE_H */
